# =============================================================================
# rhino_cw_calibration.py
#
# RHINO RFSoC 4x2 — Continuous Wave Calibration Sweep
# University of Manchester / Jodrell Bank Observatory
# Author: Mbatshi Jerry Junior Mbulawa
# Date:   2026-03-15
#
# PURPOSE
# -------
# This script sweeps a CW (sine wave) tone from 50 MHz to 200 MHz using the
# RFSoC 4x2's own DAC as a signal source, and measures the ADC's response
# at each frequency step using the rfsoc_sam overlay.
#
# It is designed to be FLEXIBLE: the tone generation backend (currently the
# DAC NCO via rfsoc_sam) is isolated in a single function so it can be
# swapped for a DDS Compiler hardware block later without changing any of
# the measurement or logging code.
#
# HARDWARE SETUP (REQUIRED BEFORE RUNNING)
# -----------------------------------------
# Connect DAC_A SMA to ADC_A SMA on the RFSoC 4x2 board using an RF coax
# cable. This creates a loopback: the tone generated by the DAC goes directly
# into the ADC input.
#
# KEY PLATFORM FACTS (from Session 1 experiments, 2026-03-04)
# ------------------------------------------------------------
# - The rfsoc_sam overlay uses DDC (Digital Down Conversion) mode.
#   The ADC DDC NCO is PERMANENTLY fixed at -1228.8 MHz by the bitstream.
#   This CANNOT be changed in Python at runtime.
#
# - IQ OUTPUT: rfsoc_sam ALWAYS outputs IQ (complex) samples.
#   There is NO way to get real samples — the mixer type is locked by
#   the xrfdc C driver. Power from IQ data must be computed as P = I^2 + Q^2.
#   The rfsoc_sam spectrum already represents this correctly in dBFS.
#
# - THE 2x IMAGE PHENOMENON (confirmed across 10 steps, Session 1):
#   When the DAC NCO is set to (1228.8 + offset) MHz, the tone peak appears
#   at 2 * offset MHz in the ADC spectrum — NOT at offset MHz.
#   Verified: DAC at 1338.8 MHz (offset=110) -> peak at 220.2 MHz (2x110)
#             DAC at 1428.8 MHz (offset=200) -> peak at 400.2 MHz (2x200)
#
#   Corrected DAC formula to place a peak at f_target MHz:
#     f_DAC = 1228.8 + (f_target / 2)
#
#   Example: peak at 75 MHz -> f_DAC = 1228.8 + 37.5 = 1266.3 MHz
#   This correction is applied inside set_tone() — do not apply it manually.
#
# - The active ADC channel for the ADC_A SMA connector is channel_22.
#   (Tile 224, ADC 0). Confirmed with 89.6 dB SNR in Session 1.
#
# - ADC hardware sample rate: 4915.2 MSPS (set by the RFSoC tile PLL).
#   rfsoc_sam does NOT apply decimation — it runs the ADC at full rate.
#   IMPORTANT: The 16x decimation to 200 MSPS is a feature of the CUSTOM
#   system_overlay bitstream (not yet deployed — blocked on licence),
#   NOT of rfsoc_sam. Do not confuse the two.
#
# - Noise floor: approximately -107.2 dBFS.
#
# HOW TO RUN
# ----------
# Copy this file to /home/xilinx/jupyter_notebooks/ on the board, then:
#   python3 rhino_cw_calibration.py
# Results are saved to rhino_cw_results.npz and rhino_cw_results.csv
# =============================================================================

import numpy as np
import matplotlib.pyplot as plt
import time
import os
import csv

# We wrap the rfsoc_sam import in a try/except so the script can also be
# run in a "dry run" simulation mode on a PC without the board connected.
try:
    from rfsoc_sam import Overlay
    BOARD_CONNECTED = True
    print("[INFO] rfsoc_sam imported successfully. Board mode active.")
except ImportError:
    BOARD_CONNECTED = False
    print("[WARNING] rfsoc_sam not found. Running in SIMULATION mode.")
    print("          All ADC readings will be synthetic. For testing only.")

# =============================================================================
# CONFIGURATION — edit these values to change the experiment parameters
# =============================================================================

# The ADC DDC NCO is permanently fixed at this frequency (MHz) by the
# rfsoc_sam bitstream. This is a hardware constant — do not change it.
DDC_NCO_MHZ = 1228.8

# ADC hardware sample rate in Hz when using rfsoc_sam.
# rfsoc_sam does NOT decimate — the ADC tile runs at its full hardware rate
# of 4915.2 MSPS. The DDC shifts the band of interest down in frequency
# but the output sample rate remains at 4915.2 MSPS.
# NOTE: 16x decimation to 200 MSPS is a feature of the CUSTOM system_overlay
# bitstream (not yet deployed), NOT rfsoc_sam.
ADC_FS_HZ = 4915.2e6   # 4915.2 MSPS — full hardware rate under rfsoc_sam

# FFT length used by rfsoc_sam internally (8192 pts confirmed in Session 1 plots).
# Bin spacing = 4915.2e6 / 8192 = ~599.6 kHz under rfsoc_sam.
# (Under the custom system_overlay with 16x decimation: 200e6 / 4096 = ~48.8 kHz)
N_FFT = 8192

# CW sweep range (MHz). Jordan specified 50–200 MHz.
SWEEP_START_MHZ = 50.0
SWEEP_STOP_MHZ  = 200.0

# Step size for the frequency sweep.
# Bin spacing at 4915.2 MSPS / 8192 pts = ~599.6 kHz under rfsoc_sam.
BIN_SPACING_MHZ = (ADC_FS_HZ / N_FFT) / 1e6   # ≈ 0.5996 MHz

# For a faster sweep during initial testing, use a coarser step (e.g. 1 MHz).
# Change this to BIN_SPACING_MHZ for the final high-resolution calibration.
SWEEP_STEP_MHZ = 1.0   # coarse sweep by default; reduce for final calibration

# Number of spectral frames to average at each frequency step.
# More frames = lower noise, but slower sweep. 20 is a good starting point.
N_FRAMES = 20

# Normalised DAC amplitude (0.0 to 1.0). 0.5 = half full scale.
# Keep below 1.0 to avoid ADC clipping. Keep above 0.1 for good SNR.
DAC_AMPLITUDE = 0.5

# Time to wait after changing the DAC NCO before taking a measurement (seconds).
# The DAC PLL needs time to re-lock to the new frequency. This is a starting
# guess — Measurement 1 (switching speed test) will give the true value.
DAC_SETTLE_TIME_S = 0.1

# Output file paths (saved in the same directory as this script)
OUTPUT_NPZ  = "rhino_cw_results.npz"
OUTPUT_CSV  = "rhino_cw_results.csv"
OUTPUT_PLOT = "rhino_cw_gain_curve.png"

# =============================================================================
# LAYER 1: TONE GENERATOR
# This is the only layer that needs to change when switching from rfsoc_sam
# NCO to a DDS Compiler hardware block. All other code stays the same.
# =============================================================================

# Global handle for the overlay and transmitter — set up in initialise_hardware()
_overlay    = None
_transmitter = None
_receiver   = None

def initialise_hardware():
    """
    Load the rfsoc_sam overlay and get handles to the transmitter and receiver.
    Must be called once before any other function.
    """
    global _overlay, _transmitter, _receiver

    if not BOARD_CONNECTED:
        # Simulation mode: nothing to initialise
        print("[SIM] Hardware initialisation skipped (simulation mode).")
        return

    print("[INFO] Loading rfsoc_sam overlay...")
    _overlay = Overlay('rfsoc_sam.bit')

    # channel_22 is the confirmed ADC channel for the ADC_A SMA connector.
    # This was verified in Session 1 (2026-03-04) with 89.6 dB SNR.
    _receiver = _overlay.radio.receiver.channel_22

    # The transmitter channel connected to DAC_A/DAC_B needs to be confirmed
    # on your specific board. Replace 'channel_X' with the correct channel.
    # TODO: update this once DAC transmitter channel is confirmed.
    _transmitter = _overlay.radio.transmitter.channel_00

    print("[INFO] Hardware initialised. Receiver: channel_22, Transmitter: channel_00")


def set_tone(freq_target_mhz, amplitude=DAC_AMPLITUDE):
    """
    Set the DAC to generate a CW tone that appears at freq_target_mhz MHz
    in the ADC output spectrum.

    THE 2x IMAGE CORRECTION:
    ------------------------
    Confirmed experimentally across 10 frequency steps (Session 1):
    When the DAC NCO is set to (DDC_NCO_MHZ + offset) MHz, the peak appears
    at 2*offset MHz in the ADC spectrum — NOT at offset MHz.

    Therefore, to place a peak at f_target MHz:
      f_DAC = DDC_NCO_MHZ + (f_target / 2)

    Example: peak at 75 MHz -> f_DAC = 1228.8 + 37.5 = 1266.3 MHz
             peak at 100 MHz -> f_DAC = 1228.8 + 50.0 = 1278.8 MHz

    THIS IS THE ONLY FUNCTION THAT NEEDS TO CHANGE when switching to a
    DDS Compiler backend. The signature stays the same; only the body changes.

    Parameters
    ----------
    freq_target_mhz : float
        Desired peak frequency in the ADC spectrum (MHz). Range: 50-200 MHz.
    amplitude : float
        Normalised DAC amplitude. 0.0 = off, 1.0 = full scale.
    """
    # Apply the 2x correction: divide target by 2 to get the correct offset
    f_offset_mhz = freq_target_mhz / 2.0
    f_dac_mhz    = DDC_NCO_MHZ + f_offset_mhz

    if not BOARD_CONNECTED:
        print(f"[SIM] set_tone: target={freq_target_mhz:.3f} MHz  "
              f"offset={f_offset_mhz:.3f} MHz  "
              f"DAC_NCO={f_dac_mhz:.3f} MHz  "
              f"amplitude={amplitude:.2f}")
        return

    # Set the DAC NCO frequency using the 2x-corrected value.
    # UpdateEvent(1) is required to push the new settings to the hardware —
    # without it the change is buffered but never applied to the DAC tile.
    _transmitter.dac_block.MixerSettings['Freq'] = f_dac_mhz

    # UpdateEvent(1) tells the xrfdc driver to apply the new MixerSettings.
    # Without this call, the change does not take effect.
    _transmitter.dac_block.UpdateEvent(1)

    # Set the output amplitude
    _transmitter.amplitude = amplitude

    # Enable the transmitter (it may have been disabled between steps)
    _transmitter.transmit_enable = True

    # Wait for the DAC PLL to re-lock to the new frequency.
    # The correct value for this sleep is determined by Measurement 1.
    time.sleep(DAC_SETTLE_TIME_S)


def disable_tone():
    """
    Turn off the DAC transmitter. Used for noise floor measurements.
    """
    if not BOARD_CONNECTED:
        print("[SIM] disable_tone: DAC transmitter disabled.")
        return
    _transmitter.transmit_enable = False
    time.sleep(0.05)   # brief settle after disabling


# =============================================================================
# LAYER 2: SPECTRUM CAPTURE
# Reads the ADC spectrum from rfsoc_sam and averages multiple frames.
# This layer is independent of how the tone is generated.
# =============================================================================

def capture_spectrum(n_frames=N_FRAMES):
    """
    Capture and average n_frames IQ spectral frames from channel_22.

    IQ POWER:
    ---------
    rfsoc_sam outputs IQ (complex) samples — the ADC is locked in DDC mode
    and cannot output real samples. The spectrum returned by rfsoc_sam with
    spectrum_type='log' already represents IQ power (I^2 + Q^2) in dBFS.
    We do not need to manually combine I and Q — the overlay does it.

    AVERAGING IN LINEAR DOMAIN:
    ---------------------------
    Averaging directly in dBFS is incorrect (geometric mean bias).
    The correct method is:
      1. Convert dBFS -> linear: P_linear = 10^(dBFS/10)
      2. Average in linear domain
      3. Convert back: dBFS = 10*log10(mean_linear)

    Returns
    -------
    spectrum_dbfs : np.ndarray
        Averaged IQ power spectrum in dBFS.
    freqs_mhz : np.ndarray
        Frequency axis in MHz (0 to ADC_FS_HZ/2).
    """
    if not BOARD_CONNECTED:
        # Simulation mode: return a synthetic spectrum with a tone peak
        # at a random frequency for testing the pipeline
        freqs_mhz = np.linspace(0, ADC_FS_HZ / 2e6, N_FFT // 2)
        spectrum = np.random.normal(-107.0, 0.5, N_FFT // 2)
        # Add a simulated tone peak (the rfsoc_sam DDC will place it at the
        # target frequency — for simulation we just pick the midpoint)
        peak_bin = N_FFT // 4
        spectrum[peak_bin] = -20.0   # simulated tone at -20 dBFS
        return spectrum, freqs_mhz

    # Set spectrum type to 'log' — this gives clean dBFS values.
    # IMPORTANT: 'power' is misleadingly named in rfsoc_sam; it gives dBFS
    # but zeros out the DC bin. 'log' is the correct choice for SNR work.
    # This was confirmed in Session 1 debugging.
    _receiver.spectrum_type = 'log'

    # Collect n_frames spectra and accumulate
    frames = []
    for _ in range(n_frames):
        frames.append(np.array(_receiver.spectrum))

    # Average in linear power domain (not dBFS) for correct averaging.
    # Step 1: convert dBFS to linear power
    frames_linear = [10.0 ** (f / 10.0) for f in frames]
    # Step 2: average
    mean_linear = np.mean(frames_linear, axis=0)
    # Step 3: convert back to dBFS
    spectrum_dbfs = 10.0 * np.log10(mean_linear)

    # Build frequency axis: bin k = k * bin_spacing_MHz
    n_bins = len(spectrum_dbfs)
    freqs_mhz = np.arange(n_bins) * (ADC_FS_HZ / N_FFT) / 1e6

    return spectrum_dbfs, freqs_mhz


def find_peak(spectrum_dbfs, freqs_mhz, target_mhz, search_window_mhz=5.0):
    """
    Find the peak bin power near target_mhz in the spectrum.

    NOTE ON 2x IMAGE:
    -----------------
    The caller is responsible for passing the CORRECT target_mhz — i.e.
    the frequency where the peak is ACTUALLY expected to appear (which is
    already 2*offset after set_tone() applies the correction). This function
    simply finds the maximum within the search window.

    The search window is 5 MHz (wider than a naive implementation) to
    robustly catch the peak given the ~0.2 MHz residual error seen in the
    Session 1 stepped-tone data (e.g. 220.2 MHz instead of exact 220.0 MHz).

    Parameters
    ----------
    spectrum_dbfs     : np.ndarray — IQ power spectrum in dBFS
    freqs_mhz         : np.ndarray — frequency axis in MHz
    target_mhz        : float      — expected peak location (MHz)
    search_window_mhz : float      — total window width in MHz (default 5.0)

    Returns
    -------
    peak_power_dbfs : float — peak bin power (dBFS), or NaN if not found
    peak_freq_mhz   : float — peak bin frequency (MHz), or NaN if not found
    """
    # Find bin indices within the search window
    mask = np.abs(freqs_mhz - target_mhz) <= (search_window_mhz / 2.0)

    if not np.any(mask):
        # No bins in window — return NaN and flag this in the log
        return np.nan, np.nan

    # Find the maximum power bin within the window
    sub_spectrum = spectrum_dbfs[mask]
    sub_freqs    = freqs_mhz[mask]
    peak_idx     = np.argmax(sub_spectrum)

    return float(sub_spectrum[peak_idx]), float(sub_freqs[peak_idx])


# =============================================================================
# LAYER 3: RESULTS LOGGER
# Saves all measurements to disk. Independent of both other layers.
# =============================================================================

def save_results(sweep_freqs, peak_powers, peak_freqs, noise_floor,
                 meta):
    """
    Save sweep results to .npz (numpy) and .csv formats.

    Parameters
    ----------
    sweep_freqs   : list of float  — target frequencies (MHz)
    peak_powers   : list of float  — measured peak power at each step (dBFS)
    peak_freqs    : list of float  — actual measured peak frequency (MHz)
    noise_floor   : float          — mean noise floor (dBFS)
    meta          : dict           — experiment metadata (amplitude, n_frames, etc.)
    """
    # Save as numpy archive (.npz) — easy to reload for analysis
    np.savez(OUTPUT_NPZ,
             sweep_freqs=np.array(sweep_freqs),
             peak_powers=np.array(peak_powers),
             peak_freqs=np.array(peak_freqs),
             noise_floor=np.array([noise_floor]))
    print(f"[INFO] Results saved to {OUTPUT_NPZ}")

    # Also save as CSV for easy inspection in a spreadsheet
    with open(OUTPUT_CSV, 'w', newline='') as f:
        writer = csv.writer(f)
        # Write metadata as comments at the top
        for k, v in meta.items():
            writer.writerow([f"# {k}", v])
        writer.writerow(["target_freq_mhz", "peak_power_dbfs",
                         "peak_freq_mhz", "snr_db"])
        for sf, pp, pf in zip(sweep_freqs, peak_powers, peak_freqs):
            snr = pp - noise_floor if not np.isnan(pp) else np.nan
            writer.writerow([f"{sf:.4f}", f"{pp:.2f}",
                             f"{pf:.4f}", f"{snr:.2f}"])
    print(f"[INFO] Results saved to {OUTPUT_CSV}")


# =============================================================================
# MEASUREMENT FUNCTIONS
# Each measurement is a self-contained function. They call Layer 1 and Layer 2
# but do not depend on each other.
# =============================================================================

def measure_switching_speed(n_trials=20):
    """
    MEASUREMENT 1: NCO Switching Speed Characterisation

    Measures how long it takes the DAC PLL to re-lock after a frequency change.
    This determines the minimum dwell time (DAC_SETTLE_TIME_S) for the sweep.

    Method:
      - Set DAC to f1 = 75 MHz in ADC spectrum
      - Issue command to switch to f2 = 100 MHz
      - Poll ADC spectrum every 10 ms; record time until stable peak at f2
      - Repeat n_trials times to get a distribution

    Returns
    -------
    switch_times_s : np.ndarray
        Array of measured switching times in seconds.
    """
    print("\n" + "="*60)
    print("MEASUREMENT 1: NCO Switching Speed")
    print("="*60)

    # These are TARGET PEAK frequencies in the ADC spectrum.
    # set_tone() applies the 2x correction internally for both.
    # f1=75 MHz -> DAC NCO = 1228.8 + 37.5 = 1266.3 MHz
    # f2=100 MHz -> DAC NCO = 1228.8 + 50.0 = 1278.8 MHz
    f1_mhz = 75.0
    f2_mhz = 100.0
    switch_times = []

    for trial in range(n_trials):
        # Step 1: set to f1 and let it settle
        set_tone(f1_mhz)
        time.sleep(0.5)   # generous initial settle

        # Step 2: issue the frequency change and start the clock
        t_start = time.perf_counter()
        set_tone(f2_mhz, amplitude=DAC_AMPLITUDE)

        # Step 3: poll until peak at f2 appears and is stable
        # "Stable" = three consecutive frames with peak within 2 dB of
        # the expected value (use the first good reading as the reference)
        stable_count = 0
        reference_power = None
        t_switch = None

        for _ in range(200):   # max 200 polls = ~2 seconds timeout
            spectrum, freqs = capture_spectrum(n_frames=1)
            peak_pwr, peak_frq = find_peak(spectrum, freqs, f2_mhz)

            if np.isnan(peak_pwr):
                time.sleep(0.01)
                continue

            if reference_power is None:
                reference_power = peak_pwr   # first good reading

            # Check if within 2 dB of reference
            if abs(peak_pwr - reference_power) < 2.0:
                stable_count += 1
            else:
                stable_count = 0
                reference_power = peak_pwr   # reset reference

            if stable_count >= 3:
                t_switch = time.perf_counter() - t_start
                break

            time.sleep(0.01)   # 10 ms between polls

        if t_switch is None:
            print(f"  Trial {trial+1:3d}: TIMEOUT (> 2 s)")
        else:
            switch_times.append(t_switch)
            print(f"  Trial {trial+1:3d}: {t_switch*1000:.1f} ms")

    switch_times = np.array(switch_times)
    if len(switch_times) > 0:
        print(f"\n  Switching time: mean={switch_times.mean()*1000:.1f} ms  "
              f"max={switch_times.max()*1000:.1f} ms  "
              f"min={switch_times.min()*1000:.1f} ms")
        print(f"  Recommended DAC_SETTLE_TIME_S: {switch_times.max()*1.5:.3f} s")
    else:
        print("  [WARNING] All trials timed out. Check hardware connection.")

    disable_tone()
    return switch_times


def measure_noise_floor(duration_s=60.0, sample_interval_s=5.0):
    """
    MEASUREMENT 4: Noise Floor Stability

    Records the ADC noise floor with no tone injected, over a period of
    duration_s seconds, sampling every sample_interval_s seconds.

    Why: A drifting noise floor means calibration must be repeated frequently.
    This measurement tells us how stable the system is over time.

    Returns
    -------
    mean_noise_dbfs : float
        Mean noise floor power across all samples and the science band bins.
    noise_over_time : np.ndarray
        Noise floor readings (dBFS) at each time sample.
    """
    print("\n" + "="*60)
    print("MEASUREMENT 4: Noise Floor Stability")
    print(f"Duration: {duration_s:.0f} s, sampling every {sample_interval_s:.0f} s")
    print("="*60)

    disable_tone()   # ensure DAC is off

    noise_readings = []
    t_start = time.time()

    # Science band: 60–85 MHz
    science_band_start = 60.0
    science_band_stop  = 85.0

    while time.time() - t_start < duration_s:
        elapsed = time.time() - t_start
        spectrum, freqs = capture_spectrum(n_frames=N_FRAMES)

        # Extract noise floor within the science band only
        mask = (freqs >= science_band_start) & (freqs <= science_band_stop)
        band_noise = np.mean(spectrum[mask])
        noise_readings.append(band_noise)

        print(f"  t={elapsed:5.1f}s  noise floor (60-85 MHz): {band_noise:.2f} dBFS")
        time.sleep(sample_interval_s)

    noise_over_time = np.array(noise_readings)
    mean_noise = float(np.mean(noise_over_time))
    drift = float(np.ptp(noise_over_time))   # peak-to-peak variation

    print(f"\n  Mean noise floor : {mean_noise:.2f} dBFS")
    print(f"  Peak-to-peak drift: {drift:.2f} dB")
    if drift > 1.0:
        print("  [WARNING] Noise floor drift > 1 dB. Consider thermal stabilisation.")
    else:
        print("  [OK] Noise floor is stable.")

    return mean_noise, noise_over_time


def measure_amplitude_linearity(freq_target_mhz=75.0, n_steps=10):
    """
    MEASUREMENT 3: Amplitude Linearity

    Sweeps DAC amplitude from 0.1 to 1.0 at a fixed target peak frequency
    and records the ADC IQ peak power at each step.

    For a linear IQ system, P = I^2 + Q^2 scales as amplitude^2.
    So doubling the amplitude adds exactly +6 dB. On a plot of
    peak_power_dBFS vs 20*log10(amplitude), a linear system gives slope=1.000.

    The 2x correction is applied inside set_tone() automatically.

    Parameters
    ----------
    freq_target_mhz : float
        Target peak frequency in ADC spectrum for this test (default 75 MHz).
        DAC NCO will be set to 1228.8 + (75/2) = 1266.3 MHz.
    n_steps : int
        Number of amplitude steps (default 10).

    Returns
    -------
    amplitudes  : np.ndarray — normalised amplitude values tested
    peak_powers : np.ndarray — measured IQ peak power at each amplitude (dBFS)
    """
    print("\n" + "="*60)
    print(f"MEASUREMENT 3: IQ Amplitude Linearity")
    print(f"Target peak: {freq_target_mhz:.1f} MHz  "
          f"(DAC NCO = {DDC_NCO_MHZ + freq_target_mhz/2:.1f} MHz)")
    print("="*60)

    amplitudes  = np.linspace(0.1, 1.0, n_steps)
    peak_powers = []

    for amp in amplitudes:
        set_tone(freq_target_mhz, amplitude=amp)
        spectrum, freqs = capture_spectrum(n_frames=N_FRAMES)
        peak_pwr, peak_frq = find_peak(spectrum, freqs, freq_target_mhz)
        peak_powers.append(peak_pwr)
        print(f"  amplitude={amp:.2f}  peak={peak_pwr:.2f} dBFS  "
              f"at {peak_frq:.3f} MHz")

    amplitudes  = np.array(amplitudes)
    peak_powers = np.array(peak_powers)

    # Check linearity: for a linear system, a doubling of amplitude (x2)
    # should give +6.02 dB. We fit a line to (20*log10(amplitude), peak_power)
    # and check the slope is close to 1.0.
    log_amp = 20.0 * np.log10(amplitudes)
    valid = ~np.isnan(peak_powers)
    if np.sum(valid) > 2:
        slope, intercept = np.polyfit(log_amp[valid], peak_powers[valid], 1)
        print(f"\n  Linearity slope: {slope:.4f} (ideal = 1.000)")
        if abs(slope - 1.0) < 0.05:
            print("  [OK] System is linear within 5%.")
        else:
            print("  [WARNING] Non-linearity detected. Check for ADC clipping.")

    disable_tone()
    return amplitudes, peak_powers


def run_gain_curve_sweep(settle_time_s=None):
    """
    MEASUREMENT 2: Main Gain Curve Sweep

    Sweeps the CW tone from SWEEP_START_MHZ to SWEEP_STOP_MHZ, recording
    the IQ peak power at each target frequency.

    2x IMAGE CORRECTION:
    --------------------
    For each target frequency f_target:
      - set_tone(f_target) sets DAC NCO to DDC_NCO_MHZ + f_target/2
      - The peak appears at f_target MHz in the IQ spectrum (2 * f_target/2)
      - find_peak() searches near f_target MHz

    The gain curve maps: target frequency (MHz) -> IQ peak power (dBFS).
    This curve is used to correct the frequency-dependent response of the
    signal chain in science observations.

    Parameters
    ----------
    settle_time_s : float or None
        DAC settle time. If None, uses DAC_SETTLE_TIME_S (set by M1).

    Returns
    -------
    sweep_freqs  : list of float — target peak frequencies (MHz)
    peak_powers  : list of float — measured IQ peak power (dBFS)
    peak_freqs   : list of float — actual measured peak frequency (MHz)
    noise_floor  : float         — pre-sweep noise floor (dBFS)
    """
    if settle_time_s is None:
        settle_time_s = DAC_SETTLE_TIME_S

    print("\n" + "="*60)
    print("MEASUREMENT 2: IQ Gain Curve Sweep")
    print(f"Target range : {SWEEP_START_MHZ}–{SWEEP_STOP_MHZ} MHz  "
          f"Step: {SWEEP_STEP_MHZ:.4f} MHz")
    print(f"DAC NCO range: "
          f"{DDC_NCO_MHZ + SWEEP_START_MHZ/2:.1f}–"
          f"{DDC_NCO_MHZ + SWEEP_STOP_MHZ/2:.1f} MHz  "
          f"(2x correction applied)")
    print(f"Frames/step  : {N_FRAMES}  Settle: {settle_time_s:.3f} s")
    print("="*60)

    # Step 1: Measure noise floor before sweep (DAC off)
    print("\n[Step 1/3] Measuring IQ noise floor (DAC off)...")
    disable_tone()
    spectrum_noise, freqs = capture_spectrum(n_frames=N_FRAMES * 2)
    noise_floor_dbfs = float(np.mean(spectrum_noise))
    print(f"  IQ noise floor: {noise_floor_dbfs:.2f} dBFS")

    # Step 2: Build target frequency list.
    # These are TARGET PEAK frequencies in the ADC spectrum.
    # set_tone() handles the 2x correction internally — no manual adjustment needed.
    n_steps_total  = int((SWEEP_STOP_MHZ - SWEEP_START_MHZ) / SWEEP_STEP_MHZ) + 1
    sweep_freqs_mhz = np.linspace(SWEEP_START_MHZ, SWEEP_STOP_MHZ, n_steps_total)

    print(f"\n[Step 2/3] Sweeping {len(sweep_freqs_mhz)} frequency steps...")

    peak_powers   = []
    peak_freqs    = []
    t_sweep_start = time.time()

    for i, f_mhz in enumerate(sweep_freqs_mhz):
        # set_tone applies: DAC NCO = DDC_NCO_MHZ + f_mhz/2
        # Peak will appear at f_mhz MHz in the IQ spectrum
        set_tone(f_mhz, amplitude=DAC_AMPLITUDE)
        time.sleep(settle_time_s)

        spectrum, freqs = capture_spectrum(n_frames=N_FRAMES)
        peak_pwr, peak_frq = find_peak(spectrum, freqs, f_mhz)
        peak_powers.append(peak_pwr)
        peak_freqs.append(peak_frq)

        snr = peak_pwr - noise_floor_dbfs if not np.isnan(peak_pwr) else np.nan

        if i % 10 == 0 or i == len(sweep_freqs_mhz) - 1:
            elapsed   = time.time() - t_sweep_start
            remaining = elapsed / (i + 1) * (len(sweep_freqs_mhz) - i - 1)
            print(f"  [{i+1:4d}/{len(sweep_freqs_mhz)}] "
                  f"target={f_mhz:7.3f} MHz  "
                  f"DAC_NCO={DDC_NCO_MHZ + f_mhz/2:.2f} MHz  "
                  f"peak={peak_pwr:7.2f} dBFS  "
                  f"SNR={snr:6.1f} dB  "
                  f"ETA: {remaining:.0f}s")

    disable_tone()
    print(f"\n  Sweep complete in {time.time()-t_sweep_start:.1f} s")

    # Step 3: Save results
    print("\n[Step 3/3] Saving results...")
    meta = {
        "date"            : time.strftime("%Y-%m-%d %H:%M:%S"),
        "overlay"         : "rfsoc_sam DDC mode — IQ output",
        "ddc_nco_mhz"     : DDC_NCO_MHZ,
        "image_correction": "2x: f_DAC = DDC_NCO + f_target/2",
        "power_type"      : "IQ power = I^2 + Q^2",
        "sweep_start_mhz" : SWEEP_START_MHZ,
        "sweep_stop_mhz"  : SWEEP_STOP_MHZ,
        "sweep_step_mhz"  : SWEEP_STEP_MHZ,
        "n_frames"        : N_FRAMES,
        "dac_amplitude"   : DAC_AMPLITUDE,
        "settle_time_s"   : settle_time_s,
        "noise_floor_dbfs": noise_floor_dbfs,
        "adc_fs_mhz"      : ADC_FS_HZ / 1e6,
        "n_fft"           : N_FFT,
    }
    save_results(list(sweep_freqs_mhz), peak_powers, peak_freqs,
                 noise_floor_dbfs, meta)

    return list(sweep_freqs_mhz), peak_powers, peak_freqs, noise_floor_dbfs


# =============================================================================
# PLOTTING
# =============================================================================

def plot_gain_curve(sweep_freqs, peak_powers, noise_floor_dbfs):
    """
    Plot the gain curve: ADC peak power vs. frequency.
    Also marks the science band (60–85 MHz) with a shaded region.

    Saves the plot to OUTPUT_PLOT and displays it if running interactively.
    """
    sweep_freqs  = np.array(sweep_freqs)
    peak_powers  = np.array(peak_powers)
    valid = ~np.isnan(peak_powers)

    fig, axes = plt.subplots(2, 1, figsize=(12, 8))
    fig.suptitle("RHINO RFSoC 4x2 — CW Calibration IQ Gain Curve\n"
                 f"rfsoc_sam DDC mode | IQ power (I²+Q²) | "
                 f"DAC NCO = {DDC_NCO_MHZ} + f_target/2 | "
                 f"Amplitude={DAC_AMPLITUDE:.2f} | N_frames={N_FRAMES}",
                 fontsize=10)

    # --- Top panel: full sweep (50–200 MHz) ---
    ax = axes[0]
    ax.plot(sweep_freqs[valid], peak_powers[valid],
            color='steelblue', linewidth=0.8, label='IQ peak power (dBFS)')
    ax.axhline(noise_floor_dbfs, color='grey', linestyle='--',
               linewidth=0.8, label=f'IQ noise floor ({noise_floor_dbfs:.1f} dBFS)')
    ax.axvspan(60, 85, alpha=0.15, color='green', label='Science band (60–85 MHz)')
    ax.set_xlabel('Target frequency (MHz)')
    ax.set_ylabel('IQ Peak Power (dBFS)')
    ax.set_title(f'Full Sweep: {SWEEP_START_MHZ}–{SWEEP_STOP_MHZ} MHz')
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)
    ax.set_xlim(SWEEP_START_MHZ, SWEEP_STOP_MHZ)

    # --- Bottom panel: science band zoom (60–85 MHz) ---
    ax2 = axes[1]
    mask_sci = (sweep_freqs >= 60) & (sweep_freqs <= 85) & valid
    if np.any(mask_sci):
        ax2.plot(sweep_freqs[mask_sci], peak_powers[mask_sci],
                 color='green', linewidth=1.0, label='IQ peak power (dBFS)')
        ax2.axhline(noise_floor_dbfs, color='grey', linestyle='--',
                    linewidth=0.8, label=f'IQ noise floor ({noise_floor_dbfs:.1f} dBFS)')
        ax2.axvline(72.5, color='orange', linestyle=':', linewidth=1.0,
                    label='Science band centre (72.5 MHz)')
        ax2.axvline(75.0, color='red', linestyle=':', linewidth=1.0,
                    label='21cm target (75 MHz)')
        ax2.set_xlabel('Target frequency (MHz)')
        ax2.set_ylabel('IQ Peak Power (dBFS)')
        ax2.set_title('Science Band Zoom: 60–85 MHz')
        ax2.legend(fontsize=8)
        ax2.grid(True, alpha=0.3)
        ax2.set_xlim(60, 85)

    plt.tight_layout()
    plt.savefig(OUTPUT_PLOT, dpi=150, bbox_inches='tight')
    print(f"[INFO] Gain curve plot saved to {OUTPUT_PLOT}")
    plt.show()


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================

def main():
    """
    Run the full CW calibration experiment in sequence:
      1. Initialise hardware
      2. Measure NCO switching speed (Measurement 1)
      3. Measure noise floor stability (Measurement 4)
      4. Measure amplitude linearity at 75 MHz (Measurement 3)
      5. Run full gain curve sweep 50–200 MHz (Measurement 2)
      6. Plot results
    """
    print("=" * 60)
    print("RHINO RFSoC 4x2 — CW Calibration Experiment")
    print("University of Manchester / Jodrell Bank Observatory")
    print(f"Start time: {time.strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    print("Platform: rfsoc_sam DDC mode")
    print("ADC output: IQ (complex) — always, fixed by bitstream")
    print(f"2x image correction: f_DAC = {DDC_NCO_MHZ} + f_target/2 MHz")
    print("=" * 60)

    # Initialise hardware (loads overlay, gets channel handles)
    initialise_hardware()

    # --- Measurement 1: Switching speed ---
    # Run this first so we know the correct settle time for the sweep.
    switch_times = measure_switching_speed(n_trials=10)
    if len(switch_times) > 0:
        # Use 1.5x the maximum measured switching time as the settle time
        recommended_settle = float(switch_times.max() * 1.5)
        print(f"\n[INFO] Setting DAC_SETTLE_TIME_S = {recommended_settle:.3f} s "
              f"based on switching speed measurement.")
    else:
        recommended_settle = DAC_SETTLE_TIME_S
        print(f"\n[WARNING] Using default settle time: {DAC_SETTLE_TIME_S} s")

    # --- Measurement 4: Noise floor stability (60 seconds) ---
    noise_mean, noise_over_time = measure_noise_floor(
        duration_s=60.0, sample_interval_s=10.0)

    # --- Measurement 3: Amplitude linearity ---
    amplitudes, amp_powers = measure_amplitude_linearity(
        freq_target_mhz=75.0, n_steps=10)

    # --- Measurement 2: Full gain curve sweep ---
    sweep_freqs, peak_powers, peak_freqs, noise_floor = run_gain_curve_sweep(
        settle_time_s=recommended_settle)

    # --- Plot results ---
    plot_gain_curve(sweep_freqs, peak_powers, noise_floor)

    print("\n" + "=" * 60)
    print("Experiment complete.")
    print(f"Results saved to: {OUTPUT_NPZ}, {OUTPUT_CSV}, {OUTPUT_PLOT}")
    print("=" * 60)


# Standard Python entry point guard:
# This ensures main() is only called when the script is run directly
# (not when it is imported as a module by the Jupyter notebook).
if __name__ == "__main__":
    main()