# =============================================================================
# rhino_cw_calibration.py
#
# RHINO RFSoC 4x2 — Continuous Wave Calibration Sweep
# University of Manchester / Jodrell Bank Observatory
# Author: Mbatshi Jerry Junior Mbulawa
# Date:   2026-03-15
#
# PURPOSE
# -------
# This script sweeps a CW (sine wave) tone from 50 MHz to 200 MHz using the
# RFSoC 4x2's own DAC as a signal source, and measures the ADC's response
# at each frequency step using the rfsoc_sam overlay.
#
# It is designed to be FLEXIBLE: the tone generation backend (currently the
# DAC NCO via rfsoc_sam) is isolated in a single function so it can be
# swapped for a DDS Compiler hardware block later without changing any of
# the measurement or logging code.
#
# HARDWARE SETUP (REQUIRED BEFORE RUNNING)
# -----------------------------------------
# Connect DAC_A SMA to ADC_A SMA on the RFSoC 4x2 board using an RF coax
# cable. This creates a loopback: the tone generated by the DAC goes directly
# into the ADC input.
#
# KEY PLATFORM FACTS (from Session 1 experiments, 2026-03-04)
# ------------------------------------------------------------
# - The rfsoc_sam overlay uses DDC (Digital Down Conversion) mode.
#   The ADC NCO is fixed at -1228.8 MHz. This CANNOT be changed in Python.
# - To observe a tone at frequency F MHz in the ADC spectrum, the DAC NCO
#   must be set to (1228.8 + F) MHz. This is the DDC offset formula.
# - The active ADC channel for the ADC_A SMA connector is channel_22.
#   (Tile 224, ADC 0). Confirmed with 89.6 dB SNR in Session 1.
# - ADC hardware sample rate: 4915.2 MSPS (set by the RFSoC tile PLL).
#   rfsoc_sam does NOT apply decimation — it runs the ADC at full rate.
#   The DDC shifts the band of interest down in frequency but does NOT
#   reduce the output sample rate seen by Python.
#   IMPORTANT: The 16x decimation to 200 MSPS is a feature of the CUSTOM
#   system_overlay bitstream (not yet deployed — blocked on licence),
#   NOT of rfsoc_sam. Do not confuse the two.
# - Noise floor: approximately -107.2 dBFS.
#
# HOW TO RUN
# ----------
# Copy this file to /home/xilinx/jupyter_notebooks/ on the board, then:
#   python3 rhino_cw_calibration.py
# Results are saved to rhino_cw_results.npz and rhino_cw_results.csv
# =============================================================================

import numpy as np
import matplotlib.pyplot as plt
import time
import os
import csv

# We wrap the rfsoc_sam import in a try/except so the script can also be
# run in a "dry run" simulation mode on a PC without the board connected.
try:
    from rfsoc_sam import Overlay
    BOARD_CONNECTED = True
    print("[INFO] rfsoc_sam imported successfully. Board mode active.")
except ImportError:
    BOARD_CONNECTED = False
    print("[WARNING] rfsoc_sam not found. Running in SIMULATION mode.")
    print("          All ADC readings will be synthetic. For testing only.")

# =============================================================================
# CONFIGURATION — edit these values to change the experiment parameters
# =============================================================================

# The rfsoc_sam DDC NCO is fixed at this frequency (MHz).
# All DAC frequencies must be offset by this amount.
DDC_OFFSET_MHZ = 1228.8

# ADC hardware sample rate in Hz when using rfsoc_sam.
# rfsoc_sam does NOT decimate — the ADC tile runs at its full hardware rate
# of 4915.2 MSPS. The DDC shifts the band of interest down in frequency
# but the output sample rate remains at 4915.2 MSPS.
# NOTE: 16x decimation to 200 MSPS is a feature of the CUSTOM system_overlay
# bitstream (not yet deployed), NOT rfsoc_sam. The value below is used only
# for computing the FFT bin spacing of the rfsoc_sam internal spectrum.
# rfsoc_sam reports its spectrum over the DDC output bandwidth — confirm
# the exact bandwidth from the overlay documentation if bin spacing matters.
ADC_FS_HZ = 4915.2e6   # 4915.2 MSPS — full hardware rate under rfsoc_sam

# FFT length used by rfsoc_sam internally.
# Bin spacing = ADC_FS_HZ / N_FFT = 4915.2e6 / 4096 ≈ 1.2 MHz under rfsoc_sam.
# (Under the custom system_overlay with 16x decimation: 200e6 / 4096 ≈ 48.8 kHz)
N_FFT = 4096

# CW sweep range (MHz). Jordan specified 50–200 MHz.
SWEEP_START_MHZ = 50.0
SWEEP_STOP_MHZ  = 200.0

# Step size for the frequency sweep.
# Using one FFT bin width ensures the tone always falls exactly on a bin,
# which avoids spectral leakage between adjacent bins.
BIN_SPACING_MHZ = (ADC_FS_HZ / N_FFT) / 1e6   # ≈ 0.0488 MHz

# For a faster sweep during initial testing, use a coarser step (e.g. 1 MHz).
# Change this to BIN_SPACING_MHZ for the final high-resolution calibration.
SWEEP_STEP_MHZ = 1.0   # coarse sweep by default; reduce for final calibration

# Number of spectral frames to average at each frequency step.
# More frames = lower noise, but slower sweep. 20 is a good starting point.
N_FRAMES = 20

# Normalised DAC amplitude (0.0 to 1.0). 0.5 = half full scale.
# Keep below 1.0 to avoid ADC clipping. Keep above 0.1 for good SNR.
DAC_AMPLITUDE = 0.5

# Time to wait after changing the DAC NCO before taking a measurement (seconds).
# The DAC PLL needs time to re-lock to the new frequency. This is a starting
# guess — Measurement 1 (switching speed test) will give the true value.
DAC_SETTLE_TIME_S = 0.1

# Output file paths (saved in the same directory as this script)
OUTPUT_NPZ  = "rhino_cw_results.npz"
OUTPUT_CSV  = "rhino_cw_results.csv"
OUTPUT_PLOT = "rhino_cw_gain_curve.png"

# =============================================================================
# LAYER 1: TONE GENERATOR
# This is the only layer that needs to change when switching from rfsoc_sam
# NCO to a DDS Compiler hardware block. All other code stays the same.
# =============================================================================

# Global handle for the overlay and transmitter — set up in initialise_hardware()
_overlay    = None
_transmitter = None
_receiver   = None

def initialise_hardware():
    """
    Load the rfsoc_sam overlay and get handles to the transmitter and receiver.
    Must be called once before any other function.
    """
    global _overlay, _transmitter, _receiver

    if not BOARD_CONNECTED:
        # Simulation mode: nothing to initialise
        print("[SIM] Hardware initialisation skipped (simulation mode).")
        return

    print("[INFO] Loading rfsoc_sam overlay...")
    _overlay = Overlay('rfsoc_sam.bit')

    # channel_22 is the confirmed ADC channel for the ADC_A SMA connector.
    # This was verified in Session 1 (2026-03-04) with 89.6 dB SNR.
    _receiver = _overlay.radio.receiver.channel_22

    # The transmitter channel connected to DAC_A/DAC_B needs to be confirmed
    # on your specific board. Replace 'channel_X' with the correct channel.
    # TODO: update this once DAC transmitter channel is confirmed.
    _transmitter = _overlay.radio.transmitter.channel_00

    print("[INFO] Hardware initialised. Receiver: channel_22, Transmitter: channel_00")


def set_tone(freq_target_mhz, amplitude=DAC_AMPLITUDE):
    """
    Set the DAC to generate a CW tone that appears at freq_target_mhz MHz
    in the ADC output spectrum.

    This is the BACKEND FUNCTION. To swap to a DDS Compiler later:
      - Replace the body of this function with AXI-Lite register writes.
      - The signature (freq_target_mhz, amplitude) stays the same.
      - Nothing else in the script changes.

    Parameters
    ----------
    freq_target_mhz : float
        Desired tone frequency in the ADC spectrum (MHz). Range: 50–200 MHz.
    amplitude : float
        Normalised DAC amplitude. 0.0 = off, 1.0 = full scale.
    """
    if not BOARD_CONNECTED:
        # Simulation mode: just print what we would do
        f_dac = DDC_OFFSET_MHZ + freq_target_mhz
        print(f"[SIM] set_tone: target={freq_target_mhz:.3f} MHz  "
              f"DAC_NCO={f_dac:.3f} MHz  amplitude={amplitude:.2f}")
        return

    # Calculate the DAC NCO frequency using the DDC offset formula:
    #   f_DAC = 1228.8 + f_target
    # This shifts the tone so that after the DDC mixes it down, it appears
    # at f_target in the ADC output spectrum.
    f_dac_mhz = DDC_OFFSET_MHZ + freq_target_mhz

    # Apply the new frequency to the DAC mixer (NCO)
    _transmitter.dac_block.MixerSettings['Freq'] = f_dac_mhz

    # UpdateEvent(1) tells the xrfdc driver to apply the new MixerSettings.
    # Without this call, the change does not take effect.
    _transmitter.dac_block.UpdateEvent(1)

    # Set the output amplitude
    _transmitter.amplitude = amplitude

    # Enable the transmitter (it may have been disabled between steps)
    _transmitter.transmit_enable = True

    # Wait for the DAC PLL to re-lock to the new frequency.
    # The correct value for this sleep is determined by Measurement 1.
    time.sleep(DAC_SETTLE_TIME_S)


def disable_tone():
    """
    Turn off the DAC transmitter. Used for noise floor measurements.
    """
    if not BOARD_CONNECTED:
        print("[SIM] disable_tone: DAC transmitter disabled.")
        return
    _transmitter.transmit_enable = False
    time.sleep(0.05)   # brief settle after disabling


# =============================================================================
# LAYER 2: SPECTRUM CAPTURE
# Reads the ADC spectrum from rfsoc_sam and averages multiple frames.
# This layer is independent of how the tone is generated.
# =============================================================================

def capture_spectrum(n_frames=N_FRAMES):
    """
    Capture and average n_frames spectral frames from channel_22.

    The rfsoc_sam overlay continuously computes an FFT of the ADC samples.
    Each call to _receiver.spectrum returns one frame. Averaging multiple
    frames reduces random noise and gives a more stable power reading.

    Returns
    -------
    spectrum_dbfs : np.ndarray, shape (N_FFT//2,)
        Averaged power spectrum in dBFS. Index k corresponds to frequency
        k * (ADC_FS_HZ / N_FFT).
    freqs_mhz : np.ndarray, shape (N_FFT//2,)
        Frequency axis in MHz corresponding to each spectrum bin.
    """
    if not BOARD_CONNECTED:
        # Simulation mode: return a synthetic spectrum with a tone peak
        # at a random frequency for testing the pipeline
        freqs_mhz = np.linspace(0, ADC_FS_HZ / 2e6, N_FFT // 2)
        spectrum = np.random.normal(-107.0, 0.5, N_FFT // 2)
        # Add a simulated tone peak (the rfsoc_sam DDC will place it at the
        # target frequency — for simulation we just pick the midpoint)
        peak_bin = N_FFT // 4
        spectrum[peak_bin] = -20.0   # simulated tone at -20 dBFS
        return spectrum, freqs_mhz

    # Set spectrum type to 'log' — this gives clean dBFS values.
    # IMPORTANT: 'power' is misleadingly named in rfsoc_sam; it gives dBFS
    # but zeros out the DC bin. 'log' is the correct choice for SNR work.
    # This was confirmed in Session 1 debugging.
    _receiver.spectrum_type = 'log'

    # Collect n_frames spectra and accumulate
    frames = []
    for _ in range(n_frames):
        frames.append(np.array(_receiver.spectrum))

    # Average in linear power domain (not dBFS) for correct averaging.
    # Step 1: convert dBFS to linear power
    frames_linear = [10.0 ** (f / 10.0) for f in frames]
    # Step 2: average
    mean_linear = np.mean(frames_linear, axis=0)
    # Step 3: convert back to dBFS
    spectrum_dbfs = 10.0 * np.log10(mean_linear)

    # Build frequency axis: bin k = k * bin_spacing_MHz
    n_bins = len(spectrum_dbfs)
    freqs_mhz = np.arange(n_bins) * (ADC_FS_HZ / N_FFT) / 1e6

    return spectrum_dbfs, freqs_mhz


def find_peak(spectrum_dbfs, freqs_mhz, target_mhz, search_window_mhz=2.0):
    """
    Find the peak bin power near a target frequency.

    We search within a window around the expected tone location to account
    for small frequency offsets. The window is ±search_window_mhz/2.

    Parameters
    ----------
    spectrum_dbfs : np.ndarray
        Power spectrum in dBFS.
    freqs_mhz : np.ndarray
        Frequency axis in MHz.
    target_mhz : float
        Expected tone frequency (MHz).
    search_window_mhz : float
        Search window width in MHz (default ±1 MHz either side).

    Returns
    -------
    peak_power_dbfs : float
        Power of the peak bin (dBFS).
    peak_freq_mhz : float
        Frequency of the peak bin (MHz).
    """
    # Find bin indices within the search window
    mask = np.abs(freqs_mhz - target_mhz) <= (search_window_mhz / 2.0)

    if not np.any(mask):
        # No bins in window — return NaN and flag this in the log
        return np.nan, np.nan

    # Find the maximum power bin within the window
    sub_spectrum = spectrum_dbfs[mask]
    sub_freqs    = freqs_mhz[mask]
    peak_idx     = np.argmax(sub_spectrum)

    return float(sub_spectrum[peak_idx]), float(sub_freqs[peak_idx])


# =============================================================================
# LAYER 3: RESULTS LOGGER
# Saves all measurements to disk. Independent of both other layers.
# =============================================================================

def save_results(sweep_freqs, peak_powers, peak_freqs, noise_floor,
                 meta):
    """
    Save sweep results to .npz (numpy) and .csv formats.

    Parameters
    ----------
    sweep_freqs   : list of float  — target frequencies (MHz)
    peak_powers   : list of float  — measured peak power at each step (dBFS)
    peak_freqs    : list of float  — actual measured peak frequency (MHz)
    noise_floor   : float          — mean noise floor (dBFS)
    meta          : dict           — experiment metadata (amplitude, n_frames, etc.)
    """
    # Save as numpy archive (.npz) — easy to reload for analysis
    np.savez(OUTPUT_NPZ,
             sweep_freqs=np.array(sweep_freqs),
             peak_powers=np.array(peak_powers),
             peak_freqs=np.array(peak_freqs),
             noise_floor=np.array([noise_floor]))
    print(f"[INFO] Results saved to {OUTPUT_NPZ}")

    # Also save as CSV for easy inspection in a spreadsheet
    with open(OUTPUT_CSV, 'w', newline='') as f:
        writer = csv.writer(f)
        # Write metadata as comments at the top
        for k, v in meta.items():
            writer.writerow([f"# {k}", v])
        writer.writerow(["target_freq_mhz", "peak_power_dbfs",
                         "peak_freq_mhz", "snr_db"])
        for sf, pp, pf in zip(sweep_freqs, peak_powers, peak_freqs):
            snr = pp - noise_floor if not np.isnan(pp) else np.nan
            writer.writerow([f"{sf:.4f}", f"{pp:.2f}",
                             f"{pf:.4f}", f"{snr:.2f}"])
    print(f"[INFO] Results saved to {OUTPUT_CSV}")


# =============================================================================
# MEASUREMENT FUNCTIONS
# Each measurement is a self-contained function. They call Layer 1 and Layer 2
# but do not depend on each other.
# =============================================================================

def measure_switching_speed(n_trials=20):
    """
    MEASUREMENT 1: NCO Switching Speed Characterisation

    Measures how long it takes the DAC PLL to re-lock after a frequency change.
    This determines the minimum dwell time (DAC_SETTLE_TIME_S) for the sweep.

    Method:
      - Set DAC to f1 = 75 MHz in ADC spectrum
      - Issue command to switch to f2 = 100 MHz
      - Poll ADC spectrum every 10 ms; record time until stable peak at f2
      - Repeat n_trials times to get a distribution

    Returns
    -------
    switch_times_s : np.ndarray
        Array of measured switching times in seconds.
    """
    print("\n" + "="*60)
    print("MEASUREMENT 1: NCO Switching Speed")
    print("="*60)

    f1_mhz = 75.0
    f2_mhz = 100.0
    switch_times = []

    for trial in range(n_trials):
        # Step 1: set to f1 and let it settle
        set_tone(f1_mhz)
        time.sleep(0.5)   # generous initial settle

        # Step 2: issue the frequency change and start the clock
        t_start = time.perf_counter()
        set_tone(f2_mhz, amplitude=DAC_AMPLITUDE)

        # Step 3: poll until peak at f2 appears and is stable
        # "Stable" = three consecutive frames with peak within 2 dB of
        # the expected value (use the first good reading as the reference)
        stable_count = 0
        reference_power = None
        t_switch = None

        for _ in range(200):   # max 200 polls = ~2 seconds timeout
            spectrum, freqs = capture_spectrum(n_frames=1)
            peak_pwr, peak_frq = find_peak(spectrum, freqs, f2_mhz)

            if np.isnan(peak_pwr):
                time.sleep(0.01)
                continue

            if reference_power is None:
                reference_power = peak_pwr   # first good reading

            # Check if within 2 dB of reference
            if abs(peak_pwr - reference_power) < 2.0:
                stable_count += 1
            else:
                stable_count = 0
                reference_power = peak_pwr   # reset reference

            if stable_count >= 3:
                t_switch = time.perf_counter() - t_start
                break

            time.sleep(0.01)   # 10 ms between polls

        if t_switch is None:
            print(f"  Trial {trial+1:3d}: TIMEOUT (> 2 s)")
        else:
            switch_times.append(t_switch)
            print(f"  Trial {trial+1:3d}: {t_switch*1000:.1f} ms")

    switch_times = np.array(switch_times)
    if len(switch_times) > 0:
        print(f"\n  Switching time: mean={switch_times.mean()*1000:.1f} ms  "
              f"max={switch_times.max()*1000:.1f} ms  "
              f"min={switch_times.min()*1000:.1f} ms")
        print(f"  Recommended DAC_SETTLE_TIME_S: {switch_times.max()*1.5:.3f} s")
    else:
        print("  [WARNING] All trials timed out. Check hardware connection.")

    disable_tone()
    return switch_times


def measure_noise_floor(duration_s=60.0, sample_interval_s=5.0):
    """
    MEASUREMENT 4: Noise Floor Stability

    Records the ADC noise floor with no tone injected, over a period of
    duration_s seconds, sampling every sample_interval_s seconds.

    Why: A drifting noise floor means calibration must be repeated frequently.
    This measurement tells us how stable the system is over time.

    Returns
    -------
    mean_noise_dbfs : float
        Mean noise floor power across all samples and the science band bins.
    noise_over_time : np.ndarray
        Noise floor readings (dBFS) at each time sample.
    """
    print("\n" + "="*60)
    print("MEASUREMENT 4: Noise Floor Stability")
    print(f"Duration: {duration_s:.0f} s, sampling every {sample_interval_s:.0f} s")
    print("="*60)

    disable_tone()   # ensure DAC is off

    noise_readings = []
    t_start = time.time()

    # Science band: 60–85 MHz
    science_band_start = 60.0
    science_band_stop  = 85.0

    while time.time() - t_start < duration_s:
        elapsed = time.time() - t_start
        spectrum, freqs = capture_spectrum(n_frames=N_FRAMES)

        # Extract noise floor within the science band only
        mask = (freqs >= science_band_start) & (freqs <= science_band_stop)
        band_noise = np.mean(spectrum[mask])
        noise_readings.append(band_noise)

        print(f"  t={elapsed:5.1f}s  noise floor (60-85 MHz): {band_noise:.2f} dBFS")
        time.sleep(sample_interval_s)

    noise_over_time = np.array(noise_readings)
    mean_noise = float(np.mean(noise_over_time))
    drift = float(np.ptp(noise_over_time))   # peak-to-peak variation

    print(f"\n  Mean noise floor : {mean_noise:.2f} dBFS")
    print(f"  Peak-to-peak drift: {drift:.2f} dB")
    if drift > 1.0:
        print("  [WARNING] Noise floor drift > 1 dB. Consider thermal stabilisation.")
    else:
        print("  [OK] Noise floor is stable.")

    return mean_noise, noise_over_time


def measure_amplitude_linearity(freq_mhz=75.0, n_steps=10):
    """
    MEASUREMENT 3: Amplitude Linearity

    Sweeps DAC amplitude from 0.1 to 1.0 at a fixed frequency and records
    the ADC peak power at each step.

    Why: Verifies that the signal chain is linear. For a linear system,
    doubling the amplitude (+6 dB) should produce exactly +6 dB in the ADC.
    Non-linearity means the gain curve depends on signal level, which
    complicates calibration.

    Parameters
    ----------
    freq_mhz : float
        Fixed tone frequency for this test (default 75 MHz).
    n_steps : int
        Number of amplitude steps (default 10).

    Returns
    -------
    amplitudes : np.ndarray
        Normalised amplitude values tested.
    peak_powers : np.ndarray
        Measured peak power at each amplitude (dBFS).
    """
    print("\n" + "="*60)
    print(f"MEASUREMENT 3: Amplitude Linearity at {freq_mhz:.1f} MHz")
    print("="*60)

    amplitudes  = np.linspace(0.1, 1.0, n_steps)
    peak_powers = []

    for amp in amplitudes:
        set_tone(freq_mhz, amplitude=amp)
        spectrum, freqs = capture_spectrum(n_frames=N_FRAMES)
        peak_pwr, peak_frq = find_peak(spectrum, freqs, freq_mhz)
        peak_powers.append(peak_pwr)
        print(f"  amplitude={amp:.2f}  peak={peak_pwr:.2f} dBFS  "
              f"at {peak_frq:.3f} MHz")

    amplitudes  = np.array(amplitudes)
    peak_powers = np.array(peak_powers)

    # Check linearity: for a linear system, a doubling of amplitude (x2)
    # should give +6.02 dB. We fit a line to (20*log10(amplitude), peak_power)
    # and check the slope is close to 1.0.
    log_amp = 20.0 * np.log10(amplitudes)
    valid = ~np.isnan(peak_powers)
    if np.sum(valid) > 2:
        slope, intercept = np.polyfit(log_amp[valid], peak_powers[valid], 1)
        print(f"\n  Linearity slope: {slope:.4f} (ideal = 1.000)")
        if abs(slope - 1.0) < 0.05:
            print("  [OK] System is linear within 5%.")
        else:
            print("  [WARNING] Non-linearity detected. Check for ADC clipping.")

    disable_tone()
    return amplitudes, peak_powers


def run_gain_curve_sweep(settle_time_s=None):
    """
    MEASUREMENT 2: Main Gain Curve Sweep (50–200 MHz)

    This is the primary calibration measurement. Sweeps the CW tone from
    SWEEP_START_MHZ to SWEEP_STOP_MHZ in steps of SWEEP_STEP_MHZ, recording
    the peak ADC power at each frequency.

    The output is the system's gain curve: how much power the ADC measures
    relative to what the DAC injects, as a function of frequency. This curve
    is used to correct for the frequency-dependent response of the signal chain
    (cables, connectors, amplifiers) in science observations.

    Parameters
    ----------
    settle_time_s : float or None
        DAC settle time in seconds. If None, uses DAC_SETTLE_TIME_S.
        Update this based on the result of Measurement 1.

    Returns
    -------
    sweep_freqs   : list of float  — target frequencies (MHz)
    peak_powers   : list of float  — measured peak power (dBFS)
    peak_freqs    : list of float  — actual measured peak frequency (MHz)
    noise_floor   : float          — mean noise floor (dBFS)
    """
    if settle_time_s is None:
        settle_time_s = DAC_SETTLE_TIME_S

    print("\n" + "="*60)
    print("MEASUREMENT 2: Gain Curve Sweep")
    print(f"Range: {SWEEP_START_MHZ}–{SWEEP_STOP_MHZ} MHz  "
          f"Step: {SWEEP_STEP_MHZ:.4f} MHz  "
          f"Frames/step: {N_FRAMES}")
    print("="*60)

    # Step 1: Measure the noise floor before the sweep starts
    # (DAC off, ADC running)
    print("\n[Step 1/3] Measuring noise floor (DAC off)...")
    disable_tone()
    spectrum_noise, freqs = capture_spectrum(n_frames=N_FRAMES * 2)
    # Use the mean across the full band as the noise floor reference
    noise_floor_dbfs = float(np.mean(spectrum_noise))
    print(f"  Noise floor: {noise_floor_dbfs:.2f} dBFS")

    # Step 2: Build the list of target frequencies, aligned to FFT bin grid
    # Bin alignment means: f_target must be a multiple of the bin spacing.
    # We round each requested frequency to the nearest bin.
    bin_hz = ADC_FS_HZ / N_FFT
    n_steps_total = int((SWEEP_STOP_MHZ - SWEEP_START_MHZ) / SWEEP_STEP_MHZ) + 1
    requested_freqs = np.linspace(SWEEP_START_MHZ, SWEEP_STOP_MHZ, n_steps_total)
    # Round to nearest bin
    sweep_freqs_hz = np.round(requested_freqs * 1e6 / bin_hz) * bin_hz
    sweep_freqs_mhz = sweep_freqs_hz / 1e6

    print(f"\n[Step 2/3] Sweeping {len(sweep_freqs_mhz)} frequency steps...")

    peak_powers = []
    peak_freqs  = []
    t_sweep_start = time.time()

    for i, f_mhz in enumerate(sweep_freqs_mhz):
        # Set the DAC NCO to produce a tone at f_mhz in the ADC spectrum
        set_tone(f_mhz, amplitude=DAC_AMPLITUDE)

        # Wait for the DAC to settle (value from Measurement 1)
        time.sleep(settle_time_s)

        # Capture and average N_FRAMES spectra
        spectrum, freqs = capture_spectrum(n_frames=N_FRAMES)

        # Find the peak near the expected tone frequency
        peak_pwr, peak_frq = find_peak(spectrum, freqs, f_mhz)
        peak_powers.append(peak_pwr)
        peak_freqs.append(peak_frq)

        # SNR = tone peak power minus noise floor
        snr = peak_pwr - noise_floor_dbfs if not np.isnan(peak_pwr) else np.nan

        # Progress report every 10 steps
        if i % 10 == 0 or i == len(sweep_freqs_mhz) - 1:
            elapsed = time.time() - t_sweep_start
            remaining = elapsed / (i + 1) * (len(sweep_freqs_mhz) - i - 1)
            print(f"  [{i+1:4d}/{len(sweep_freqs_mhz)}] "
                  f"f={f_mhz:7.3f} MHz  "
                  f"peak={peak_pwr:7.2f} dBFS  "
                  f"SNR={snr:6.1f} dB  "
                  f"ETA: {remaining:.0f}s")

    disable_tone()
    total_time = time.time() - t_sweep_start
    print(f"\n  Sweep complete in {total_time:.1f} s")

    # Step 3: Save results
    print("\n[Step 3/3] Saving results...")
    meta = {
        "date": time.strftime("%Y-%m-%d %H:%M:%S"),
        "sweep_start_mhz": SWEEP_START_MHZ,
        "sweep_stop_mhz": SWEEP_STOP_MHZ,
        "sweep_step_mhz": SWEEP_STEP_MHZ,
        "n_frames": N_FRAMES,
        "dac_amplitude": DAC_AMPLITUDE,
        "dac_settle_time_s": settle_time_s,
        "noise_floor_dbfs": noise_floor_dbfs,
        "ddc_offset_mhz": DDC_OFFSET_MHZ,
        "adc_fs_mhz": ADC_FS_HZ / 1e6,
        "n_fft": N_FFT,
    }
    save_results(list(sweep_freqs_mhz), peak_powers, peak_freqs,
                 noise_floor_dbfs, meta)

    return list(sweep_freqs_mhz), peak_powers, peak_freqs, noise_floor_dbfs


# =============================================================================
# PLOTTING
# =============================================================================

def plot_gain_curve(sweep_freqs, peak_powers, noise_floor_dbfs):
    """
    Plot the gain curve: ADC peak power vs. frequency.
    Also marks the science band (60–85 MHz) with a shaded region.

    Saves the plot to OUTPUT_PLOT and displays it if running interactively.
    """
    sweep_freqs  = np.array(sweep_freqs)
    peak_powers  = np.array(peak_powers)
    valid = ~np.isnan(peak_powers)

    fig, axes = plt.subplots(2, 1, figsize=(12, 8))
    fig.suptitle("RHINO RFSoC 4x2 — CW Calibration Gain Curve\n"
                 f"DAC amplitude={DAC_AMPLITUDE:.2f}, "
                 f"N_frames={N_FRAMES}, "
                 f"Step={SWEEP_STEP_MHZ:.3f} MHz",
                 fontsize=12)

    # --- Top panel: full sweep (50–200 MHz) ---
    ax = axes[0]
    ax.plot(sweep_freqs[valid], peak_powers[valid],
            color='steelblue', linewidth=0.8, label='Peak power (dBFS)')
    ax.axhline(noise_floor_dbfs, color='grey', linestyle='--',
               linewidth=0.8, label=f'Noise floor ({noise_floor_dbfs:.1f} dBFS)')
    # Shade the science band
    ax.axvspan(60, 85, alpha=0.15, color='green', label='Science band (60–85 MHz)')
    ax.set_xlabel('Frequency (MHz)')
    ax.set_ylabel('ADC Peak Power (dBFS)')
    ax.set_title('Full Sweep: 50–200 MHz')
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)
    ax.set_xlim(SWEEP_START_MHZ, SWEEP_STOP_MHZ)

    # --- Bottom panel: science band zoom (60–85 MHz) ---
    ax2 = axes[1]
    mask_sci = (sweep_freqs >= 60) & (sweep_freqs <= 85) & valid
    if np.any(mask_sci):
        ax2.plot(sweep_freqs[mask_sci], peak_powers[mask_sci],
                 color='green', linewidth=1.0, label='Peak power (dBFS)')
        ax2.axhline(noise_floor_dbfs, color='grey', linestyle='--',
                    linewidth=0.8, label=f'Noise floor ({noise_floor_dbfs:.1f} dBFS)')
        # Mark the 21cm target (75 MHz)
        ax2.axvline(75.0, color='red', linestyle=':', linewidth=1.0,
                    label='21cm target (75 MHz)')
        ax2.set_xlabel('Frequency (MHz)')
        ax2.set_ylabel('ADC Peak Power (dBFS)')
        ax2.set_title('Science Band Zoom: 60–85 MHz')
        ax2.legend(fontsize=8)
        ax2.grid(True, alpha=0.3)
        ax2.set_xlim(60, 85)

    plt.tight_layout()
    plt.savefig(OUTPUT_PLOT, dpi=150, bbox_inches='tight')
    print(f"[INFO] Gain curve plot saved to {OUTPUT_PLOT}")
    plt.show()


# =============================================================================
# MAIN ENTRY POINT
# =============================================================================

def main():
    """
    Run the full CW calibration experiment in sequence:
      1. Initialise hardware
      2. Measure NCO switching speed (Measurement 1)
      3. Measure noise floor stability (Measurement 4)
      4. Measure amplitude linearity at 75 MHz (Measurement 3)
      5. Run full gain curve sweep 50–200 MHz (Measurement 2)
      6. Plot results
    """
    print("=" * 60)
    print("RHINO RFSoC 4x2 — CW Calibration Experiment")
    print("University of Manchester / Jodrell Bank Observatory")
    print(f"Start time: {time.strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)

    # Initialise hardware (loads overlay, gets channel handles)
    initialise_hardware()

    # --- Measurement 1: Switching speed ---
    # Run this first so we know the correct settle time for the sweep.
    switch_times = measure_switching_speed(n_trials=10)
    if len(switch_times) > 0:
        # Use 1.5x the maximum measured switching time as the settle time
        recommended_settle = float(switch_times.max() * 1.5)
        print(f"\n[INFO] Setting DAC_SETTLE_TIME_S = {recommended_settle:.3f} s "
              f"based on switching speed measurement.")
    else:
        recommended_settle = DAC_SETTLE_TIME_S
        print(f"\n[WARNING] Using default settle time: {DAC_SETTLE_TIME_S} s")

    # --- Measurement 4: Noise floor stability (60 seconds) ---
    noise_mean, noise_over_time = measure_noise_floor(
        duration_s=60.0, sample_interval_s=10.0)

    # --- Measurement 3: Amplitude linearity ---
    amplitudes, amp_powers = measure_amplitude_linearity(
        freq_mhz=75.0, n_steps=10)

    # --- Measurement 2: Full gain curve sweep ---
    sweep_freqs, peak_powers, peak_freqs, noise_floor = run_gain_curve_sweep(
        settle_time_s=recommended_settle)

    # --- Plot results ---
    plot_gain_curve(sweep_freqs, peak_powers, noise_floor)

    print("\n" + "=" * 60)
    print("Experiment complete.")
    print(f"Results saved to: {OUTPUT_NPZ}, {OUTPUT_CSV}, {OUTPUT_PLOT}")
    print("=" * 60)


# Standard Python entry point guard:
# This ensures main() is only called when the script is run directly
# (not when it is imported as a module by the Jupyter notebook).
if __name__ == "__main__":
    main()